_doc_: "Configuration parameters for the driver behavior"

# Behavior:
driver_revolution_signal_blind_time:
  value: 2
  c_type: int
  comment: "Time in millis where interrupts are ignored because the signal might be fuzzy and result in multiple signal edges."
driver_braking_deceleration_offset_rpm:
  value: 15 # 0.2 km/h
  c_type: int
  comment: "Offset in RPM for the deceleration braking behavior. If the negative difference between current and target speed (as absolute value) exceeds this offset, braking behavior will start."
driver_braking_overshoot_limit_rpm:
  value: 361 # 5 km/h
  c_type: int
  comment: "Limit in RPM for the overshoot braking behavior. As soon as the actual speed is above this value over the target speed, braking behavior will start."
driver_panel_display_speed_refresh_delay_ms:
  value: 100 # 10 fps
  c_type: int
  comment: "Delay in millis between speed value updates on the display. When the mode changes the value will be updated immediately."
driver_throttle_reading_reaction_threshold_rpm:
  value: 22 # 0.3 km/h
  c_type: int
  comment: "Threshold in RPM reacting to target speed changes read from the throttle lever. If the difference between reading and current target speed (as absolute value) exceeds this threshold, the target speed will be updated. This only affects the manual control mode."