name: Connector CI

on:
  push:
    branches: [ "*" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # manual trigger

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies

    - name: Install dependencies
      working-directory: ./connector
      run: pip install -r requirements.txt

    - name: Install linter
      run: pip install pylint

    - name: Lint with Pylint
      working-directory: ./connector
      run: pylint --rcfile=./pylintrc.toml -j 0 --output-format=github **/*.py

  package:
    name: Packaging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies

    - name: Install dependencies
      working-directory: ./connector
      run: |
        pip install -r requirements.txt
        pip install build

    - name: Package
      working-directory: ./connector
      run: python -m build

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: connector-package
        path: ./connector/dist/
        if-no-files-found: error

  release:
    if: startsWith(github.event.ref, 'refs/tags/v')
    name: Releasing
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - package
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: connector-package
          path: dist/

      - name: Attach files to release
        uses: softprops/action-gh-release@v3
        with:
          append_body: false
          fail_on_unmatched_files: true
          files: |
            dist/*